name: Cypress Tests - e2e-tests-front-end

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.json'
      - '**.yml'
      - 'cypress/**'
      - 'package.json'
      - 'cypress.config.js'

jobs:
  e2e-tests-front-end-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:headless